/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;
import model.*;




/**
 *
 * @author HP
 */
public class DisplayJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DisplayJPanel
     * 
     */
    Person person;
    Driver driver;
    Doctor doctor;
    Patient patient;
    Insurance insurance;
    Vehicle vehicle;
    Address address;
    
    
    public DisplayJPanel(Person person,Address address,Insurance insurance,Patient patient, Doctor doctor, Driver driver, Vehicle vehicle) {
        initComponents();
        this.person = person ;
        this.driver = driver ;
        this.address = address ;
        this.doctor = doctor;
        this.insurance = insurance ;
        this.patient = patient;
        this.vehicle = vehicle;
        
        
        
        
        displayPatient();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPerson = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblOccupation = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblSsn = new javax.swing.JLabel();
        lblWebsiteUrl = new javax.swing.JLabel();
        lblEmergencyContact = new javax.swing.JLabel();
        lblGpsLocation = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblState = new javax.swing.JLabel();
        lblCountry = new javax.swing.JLabel();
        lblDriversName2 = new javax.swing.JLabel();
        lblLicenseNo2 = new javax.swing.JLabel();
        lblDriversDetails2 = new javax.swing.JLabel();
        lblInsuranceCoverage = new javax.swing.JLabel();
        lblCorporateId = new javax.swing.JLabel();
        lblAddress1 = new javax.swing.JLabel();
        lblPremium = new javax.swing.JLabel();
        lblDeductable = new javax.swing.JLabel();
        lblBenefits = new javax.swing.JLabel();
        lblDoctorsDetails = new javax.swing.JLabel();
        lblName1 = new javax.swing.JLabel();
        lblDoctorsId = new javax.swing.JLabel();
        lblSpecialisedIn = new javax.swing.JLabel();
        lblPhoneNo = new javax.swing.JLabel();
        lblAddress2 = new javax.swing.JLabel();
        lblEmail1 = new javax.swing.JLabel();
        lblWebsite = new javax.swing.JLabel();
        lblVehicleRegistration = new javax.swing.JLabel();
        lblCarCompany = new javax.swing.JLabel();
        lblModel = new javax.swing.JLabel();
        lblChasisNo = new javax.swing.JLabel();
        lblSerial = new javax.swing.JLabel();
        lblPatientId = new javax.swing.JLabel();
        lblPrimaryDoctor = new javax.swing.JLabel();
        lblDateOfLastVisit = new javax.swing.JLabel();
        lblDateOfNextAppointment = new javax.swing.JLabel();
        lblAllergies = new javax.swing.JLabel();
        lblMedication = new javax.swing.JLabel();
        lblPatientDetails = new javax.swing.JLabel();
        lblAddress3 = new javax.swing.JLabel();
        lblOutName = new javax.swing.JLabel();
        lblOutGender = new javax.swing.JLabel();
        lblOutAge = new javax.swing.JLabel();
        lblOutOccupation = new javax.swing.JLabel();
        lblOutAddress = new javax.swing.JLabel();
        lblOutEmail = new javax.swing.JLabel();
        lblOutSsn = new javax.swing.JLabel();
        lblOutWebsiteUrl = new javax.swing.JLabel();
        lblOutEmergencyContact = new javax.swing.JLabel();
        lblOutGpsLocation = new javax.swing.JLabel();
        lblOutCity = new javax.swing.JLabel();
        lblOutState = new javax.swing.JLabel();
        lblOutCountry = new javax.swing.JLabel();
        lblOutCorporateId = new javax.swing.JLabel();
        lblOutAddress2 = new javax.swing.JLabel();
        lblOutPremium = new javax.swing.JLabel();
        lblOutDeductable = new javax.swing.JLabel();
        lblOutBenefits = new javax.swing.JLabel();
        lblOutDriversName = new javax.swing.JLabel();
        lblOutLicenseNo = new javax.swing.JLabel();
        lblOutCarCompany = new javax.swing.JLabel();
        lblOutModel = new javax.swing.JLabel();
        lblOutChasisNo = new javax.swing.JLabel();
        lblOutSerial = new javax.swing.JLabel();
        lblOutName2 = new javax.swing.JLabel();
        lblOutDoctorsId = new javax.swing.JLabel();
        lblOutSpecialisedIn = new javax.swing.JLabel();
        lblOutPhoneNo = new javax.swing.JLabel();
        lblOutAddress3 = new javax.swing.JLabel();
        lblOutEmail2 = new javax.swing.JLabel();
        lblOutWebsite = new javax.swing.JLabel();
        lblOutPatientId = new javax.swing.JLabel();
        lblOutPrimaryDoctor = new javax.swing.JLabel();
        lblOutDateOfLastVisit = new javax.swing.JLabel();
        lblOutDateOfNextAppointment = new javax.swing.JLabel();
        lblAllerigiesOut = new javax.swing.JLabel();
        lblMedicationOut = new javax.swing.JLabel();
        lblEmergencyContact2 = new javax.swing.JLabel();
        lblOutEmergencyContact2 = new javax.swing.JLabel();

        lblPerson.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblPerson.setText("Person details");

        lblName.setText("Name");

        lblGender.setText("Gender");

        lblAge.setText("Age");

        lblOccupation.setText("Occupation");

        lblAddress.setText("Address");

        lblEmail.setText("Email");

        lblSsn.setText("SSN");

        lblWebsiteUrl.setText("Website URL");

        lblEmergencyContact.setText("Emergency contact");

        lblGpsLocation.setText("GPS location");

        lblCity.setText("City");

        lblState.setText("State");

        lblCountry.setText("Country");

        lblDriversName2.setText("Drivers name");

        lblLicenseNo2.setText("License no");

        lblDriversDetails2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblDriversDetails2.setText("Drivers details");

        lblInsuranceCoverage.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblInsuranceCoverage.setText("Insurance Coverage");

        lblCorporateId.setText("Corporate id");

        lblAddress1.setText("Address");

        lblPremium.setText("Premium");

        lblDeductable.setText("Deductable");

        lblBenefits.setText("Benefits");

        lblDoctorsDetails.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblDoctorsDetails.setText("Doctors details");

        lblName1.setText("Name");

        lblDoctorsId.setText("Doctors id");

        lblSpecialisedIn.setText("Specialised in");

        lblPhoneNo.setText("Phone no");

        lblAddress2.setText("Address");

        lblEmail1.setText("Email");

        lblWebsite.setText("Website");

        lblVehicleRegistration.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblVehicleRegistration.setText("Vehicle Registration");

        lblCarCompany.setText("Car Company");

        lblModel.setText("Model");

        lblChasisNo.setText("Chasis No");

        lblSerial.setText("Serial");

        lblPatientId.setText("Patient id");

        lblPrimaryDoctor.setText("Primary doctor");

        lblDateOfLastVisit.setText("Date of last visit");

        lblDateOfNextAppointment.setText("Date of next appointment");

        lblAllergies.setText("Allergies");

        lblMedication.setText("Medication");

        lblPatientDetails.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblPatientDetails.setText("Patient details");

        lblAddress3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblAddress3.setText("Address");

        lblEmergencyContact2.setText("Emergency contact2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGender)
                            .addComponent(lblOccupation)
                            .addComponent(lblAddress)
                            .addComponent(lblName)
                            .addComponent(lblAge))
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblOutName, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblOutAddress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                .addComponent(lblOutOccupation, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblOutAge, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblOutGender, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(lblPerson))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmail)
                            .addComponent(lblEmergencyContact)
                            .addComponent(lblWebsiteUrl)
                            .addComponent(lblSsn)
                            .addComponent(lblEmergencyContact2))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblOutEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblOutEmergencyContact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblOutWebsiteUrl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblOutSsn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblOutEmergencyContact2, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblGpsLocation)
                                    .addComponent(lblState, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCity, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCountry, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblOutCity, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblOutGpsLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(87, 87, 87))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(32, 32, 32)
                                                .addComponent(lblOutState, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(43, 43, 43)
                                                .addComponent(lblOutCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(95, 95, 95))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblInsuranceCoverage)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(lblBenefits))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblAddress1)
                                            .addComponent(lblPremium)
                                            .addComponent(lblDeductable)
                                            .addComponent(lblCorporateId))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(58, 58, 58)
                                                .addComponent(lblOutCorporateId, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(38, 38, 38)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblOutAddress2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(lblOutBenefits, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                                                        .addComponent(lblOutDeductable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(lblAddress3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblDriversName2)
                                            .addComponent(lblLicenseNo2))
                                        .addGap(44, 44, 44)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblOutDriversName, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblOutLicenseNo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addComponent(lblDriversDetails2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(90, 90, 90)
                                        .addComponent(lblOutPremium, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(7, 7, 7)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblPhoneNo, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblWebsite)
                                    .addGap(52, 52, 52)
                                    .addComponent(lblOutWebsite, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(1, 1, 1)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblVehicleRegistration)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(lblCarCompany)
                                                    .addComponent(lblModel, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblChasisNo, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblSerial, javax.swing.GroupLayout.Alignment.LEADING))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(lblOutCarCompany, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                                                        .addComponent(lblOutModel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(lblOutChasisNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    .addComponent(lblOutSerial, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblName1)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(67, 67, 67)
                                                .addComponent(lblOutName2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(33, 33, 33))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(57, 57, 57)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblOutEmail2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblDoctorsDetails)))))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblOutAddress3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(lblSpecialisedIn)
                                            .addGap(26, 26, 26)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblOutPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblOutSpecialisedIn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(69, 69, 69)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDateOfNextAppointment)
                                    .addComponent(lblPrimaryDoctor)
                                    .addComponent(lblPatientId)
                                    .addComponent(lblDateOfLastVisit))
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblOutPrimaryDoctor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblOutDateOfLastVisit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                                    .addComponent(lblOutDateOfNextAppointment, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblOutPatientId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(lblPatientDetails))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMedication)
                                    .addComponent(lblAllergies))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblAllerigiesOut, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                                    .addComponent(lblMedicationOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDoctorsId)
                        .addGap(44, 44, 44)
                        .addComponent(lblOutDoctorsId, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblAddress2)
                    .addComponent(lblEmail1))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(lblPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblGender)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblOutName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(lblOutGender, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAge)
                    .addComponent(lblOutAge, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOccupation)
                    .addComponent(lblOutOccupation, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddress)
                    .addComponent(lblOutAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(lblOutEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblSsn)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblOutSsn, javax.swing.GroupLayout.DEFAULT_SIZE, 12, Short.MAX_VALUE)
                        .addGap(16, 16, 16)))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWebsiteUrl)
                    .addComponent(lblOutWebsiteUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblEmergencyContact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblOutEmergencyContact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmergencyContact2)
                    .addComponent(lblOutEmergencyContact2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblAddress3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblGpsLocation))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblOutGpsLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblOutCity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblState)
                            .addComponent(lblOutState, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCountry)
                            .addComponent(lblOutCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDoctorsDetails)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblName1)
                            .addComponent(lblOutName2, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblDoctorsId)
                            .addComponent(lblOutDoctorsId, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSpecialisedIn)
                            .addComponent(lblOutSpecialisedIn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPhoneNo)
                            .addComponent(lblOutPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblOutAddress3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAddress2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblEmail1)
                                        .addGap(24, 24, 24))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblOutEmail2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblWebsite)
                                    .addComponent(lblOutWebsite, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblPatientDetails))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(lblVehicleRegistration)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblCarCompany)
                                    .addComponent(lblOutCarCompany, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblModel)
                                    .addComponent(lblOutModel, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblChasisNo)
                                    .addComponent(lblOutChasisNo, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblSerial)
                                    .addComponent(lblOutSerial, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblPatientId)
                                    .addComponent(lblOutPatientId, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblPrimaryDoctor)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblDateOfLastVisit)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblDateOfNextAppointment)
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblOutPrimaryDoctor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblOutDateOfLastVisit, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblOutDateOfNextAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblAllergies)
                                    .addComponent(lblAllerigiesOut, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblMedication)
                                    .addComponent(lblMedicationOut, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblInsuranceCoverage)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCorporateId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblOutCorporateId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAddress1)
                                .addGap(18, 18, 18)
                                .addComponent(lblPremium))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblOutAddress2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblOutPremium, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDeductable)
                            .addComponent(lblOutDeductable, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBenefits)
                            .addComponent(lblOutBenefits, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addComponent(lblDriversDetails2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDriversName2)
                            .addComponent(lblOutDriversName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLicenseNo2)
                            .addComponent(lblOutLicenseNo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAddress1;
    private javax.swing.JLabel lblAddress2;
    private javax.swing.JLabel lblAddress3;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblAllergies;
    private javax.swing.JLabel lblAllerigiesOut;
    private javax.swing.JLabel lblBenefits;
    private javax.swing.JLabel lblCarCompany;
    private javax.swing.JLabel lblChasisNo;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCorporateId;
    private javax.swing.JLabel lblCountry;
    private javax.swing.JLabel lblDateOfLastVisit;
    private javax.swing.JLabel lblDateOfNextAppointment;
    private javax.swing.JLabel lblDeductable;
    private javax.swing.JLabel lblDoctorsDetails;
    private javax.swing.JLabel lblDoctorsId;
    private javax.swing.JLabel lblDriversDetails2;
    private javax.swing.JLabel lblDriversName2;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmail1;
    private javax.swing.JLabel lblEmergencyContact;
    private javax.swing.JLabel lblEmergencyContact2;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblGpsLocation;
    private javax.swing.JLabel lblInsuranceCoverage;
    private javax.swing.JLabel lblLicenseNo2;
    private javax.swing.JLabel lblMedication;
    private javax.swing.JLabel lblMedicationOut;
    private javax.swing.JLabel lblModel;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblName1;
    private javax.swing.JLabel lblOccupation;
    private javax.swing.JLabel lblOutAddress;
    private javax.swing.JLabel lblOutAddress2;
    private javax.swing.JLabel lblOutAddress3;
    private javax.swing.JLabel lblOutAge;
    private javax.swing.JLabel lblOutBenefits;
    private javax.swing.JLabel lblOutCarCompany;
    private javax.swing.JLabel lblOutChasisNo;
    private javax.swing.JLabel lblOutCity;
    private javax.swing.JLabel lblOutCorporateId;
    private javax.swing.JLabel lblOutCountry;
    private javax.swing.JLabel lblOutDateOfLastVisit;
    private javax.swing.JLabel lblOutDateOfNextAppointment;
    private javax.swing.JLabel lblOutDeductable;
    private javax.swing.JLabel lblOutDoctorsId;
    private javax.swing.JLabel lblOutDriversName;
    private javax.swing.JLabel lblOutEmail;
    private javax.swing.JLabel lblOutEmail2;
    private javax.swing.JLabel lblOutEmergencyContact;
    private javax.swing.JLabel lblOutEmergencyContact2;
    private javax.swing.JLabel lblOutGender;
    private javax.swing.JLabel lblOutGpsLocation;
    private javax.swing.JLabel lblOutLicenseNo;
    private javax.swing.JLabel lblOutModel;
    private javax.swing.JLabel lblOutName;
    private javax.swing.JLabel lblOutName2;
    private javax.swing.JLabel lblOutOccupation;
    private javax.swing.JLabel lblOutPatientId;
    private javax.swing.JLabel lblOutPhoneNo;
    private javax.swing.JLabel lblOutPremium;
    private javax.swing.JLabel lblOutPrimaryDoctor;
    private javax.swing.JLabel lblOutSerial;
    private javax.swing.JLabel lblOutSpecialisedIn;
    private javax.swing.JLabel lblOutSsn;
    private javax.swing.JLabel lblOutState;
    private javax.swing.JLabel lblOutWebsite;
    private javax.swing.JLabel lblOutWebsiteUrl;
    private javax.swing.JLabel lblPatientDetails;
    private javax.swing.JLabel lblPatientId;
    private javax.swing.JLabel lblPerson;
    private javax.swing.JLabel lblPhoneNo;
    private javax.swing.JLabel lblPremium;
    private javax.swing.JLabel lblPrimaryDoctor;
    private javax.swing.JLabel lblSerial;
    private javax.swing.JLabel lblSpecialisedIn;
    private javax.swing.JLabel lblSsn;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblVehicleRegistration;
    private javax.swing.JLabel lblWebsite;
    private javax.swing.JLabel lblWebsiteUrl;
    // End of variables declaration//GEN-END:variables

private void displayPatient() {
    
    lblOutName.setText(person.getName());
    lblOutAddress.setText(person.getAddress());
    lblOutGender.setText(person.getGender());
    lblOutAge.setText(person.getAge());
    lblOutEmail.setText(person.getEmail());
    lblOutWebsiteUrl.setText(person.getWebsiteUrl());
    lblOutEmergencyContact.setText(person.getEmergencyContact());
    lblOutEmergencyContact2.setText(person.getEmergencyContact2());
    lblOutSsn.setText(person.getSsn());
    lblOutOccupation.setText(person.getOccupation());
    
    
    
    lblOutGpsLocation.setText(address.getGpsLocation());
    lblOutCity.setText(address.getCity());
    lblOutState.setText(address.getState());
    lblOutCountry.setText(address.getCountry());
    
    
    
    lblOutBenefits.setText(insurance.getBenefits());
    lblOutCorporateId.setText(insurance.getCorporateID());
    lblOutAddress2.setText(insurance.getAddress());
    lblOutPremium.setText(insurance.getPremium());
    lblOutDeductable.setText(insurance.getDeductable());
    
    
    lblOutDriversName.setText(driver.getDriversName());
    lblOutLicenseNo.setText(driver.getLicenseNo());
    
    
    lblOutCarCompany.setText(vehicle.getCarCompany());
    lblOutModel.setText(vehicle.getModel());
    lblOutChasisNo.setText(vehicle.getChasisNo());
    lblOutSerial.setText(vehicle.getSerial());
    
    
    
    lblOutName2.setText(doctor.getName());
    lblOutDoctorsId.setText(doctor.getDoctorsId());
    lblOutSpecialisedIn.setText(doctor.getSpecialisedIn());
    lblOutPhoneNo.setText(doctor.getPhoneNo());
    lblOutAddress3.setText(doctor.getAddress());
    lblOutEmail2.setText(doctor.getEmail());
    lblOutWebsite.setText(doctor.getWebsite());
    
    
    lblOutPatientId.setText(patient.getPatientId());
    lblOutPrimaryDoctor.setText(patient.getPrimaryDoctor());
    lblOutDateOfLastVisit.setText(patient.getDateOfLastVisit());
    lblOutDateOfNextAppointment.setText(patient.getDateOfNextAppointment());
    
    
    
    
    
    
    
    //txtDescription.setText(product.getDescr());
    //txtAvailability.setText(product.getAvailNum());
   // txtPrice.setText(product.getPrice());
    
    
    
    
    }



}
