/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import model.Address;
import model.Doctor;
import model.Driver;
import model.Insurance;
import model.Patient;
import model.Person;
import model.Vehicle;
import java.io.*;


/**
 *
 * @author HP
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    
    Person person;
    Address address;
    Doctor doctor;
    Driver driver;
    Insurance insurance;
    Patient patient;
    Vehicle vehicle;
    
    
    public MainJFrame() {
        initComponents();
        person = new Person();
        
        address= new Address();
        insurance= new Insurance();
        doctor= new Doctor();
        driver= new Driver();
        
        patient= new Patient();
        vehicle= new Vehicle();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        btnPerson = new javax.swing.JButton();
        btnAddress = new javax.swing.JButton();
        btnDriver = new javax.swing.JButton();
        btnVehicleRegistration = new javax.swing.JButton();
        btnPatient = new javax.swing.JButton();
        btnDoctor = new javax.swing.JButton();
        btnInsuranceCoverage = new javax.swing.JButton();
        btnDisplayPatientReport = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnPerson.setText("Person");
        btnPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonActionPerformed(evt);
            }
        });

        btnAddress.setText("Address");
        btnAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddressActionPerformed(evt);
            }
        });

        btnDriver.setText("Driver");
        btnDriver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDriverActionPerformed(evt);
            }
        });

        btnVehicleRegistration.setText("Vehicle Registration ");
        btnVehicleRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVehicleRegistrationActionPerformed(evt);
            }
        });

        btnPatient.setText("Patient");
        btnPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientActionPerformed(evt);
            }
        });

        btnDoctor.setText("Doctor");
        btnDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoctorActionPerformed(evt);
            }
        });

        btnInsuranceCoverage.setText("Insurance Coverage");
        btnInsuranceCoverage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsuranceCoverageActionPerformed(evt);
            }
        });

        btnDisplayPatientReport.setText("Display Patient Report");
        btnDisplayPatientReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayPatientReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnInsuranceCoverage, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDoctor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPatient, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDriver, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPerson, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVehicleRegistration, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDisplayPatientReport, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnPerson)
                .addGap(26, 26, 26)
                .addComponent(btnAddress)
                .addGap(29, 29, 29)
                .addComponent(btnDriver)
                .addGap(26, 26, 26)
                .addComponent(btnVehicleRegistration)
                .addGap(30, 30, 30)
                .addComponent(btnPatient)
                .addGap(31, 31, 31)
                .addComponent(btnDoctor)
                .addGap(29, 29, 29)
                .addComponent(btnInsuranceCoverage)
                .addGap(32, 32, 32)
                .addComponent(btnDisplayPatientReport)
                .addContainerGap(175, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 664, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 591, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonActionPerformed
        // TODO add your handling code here:
         PersonJPanel personPanel = new PersonJPanel(person);
       jSplitPane1.setRightComponent(personPanel);
       
    }//GEN-LAST:event_btnPersonActionPerformed

    private void btnAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddressActionPerformed
        // TODO add your handling code here:
        AddressJPanel addresspanel = new AddressJPanel(address);
       jSplitPane1.setRightComponent(addresspanel);
    }//GEN-LAST:event_btnAddressActionPerformed

    private void btnDriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDriverActionPerformed
        // TODO add your handling code here:
        DriverJPanel driverPanel = new DriverJPanel(driver);
       jSplitPane1.setRightComponent(driverPanel);
    }//GEN-LAST:event_btnDriverActionPerformed

    private void btnVehicleRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVehicleRegistrationActionPerformed
        // TODO add your handling code here:
        VehicleJPanel vehiclePanel = new VehicleJPanel(vehicle);
                jSplitPane1.setRightComponent(vehiclePanel);
    }//GEN-LAST:event_btnVehicleRegistrationActionPerformed

    private void btnPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientActionPerformed
        // TODO add your handling code here:
        PatientJPanel patientPanel = new PatientJPanel(patient);
        jSplitPane1.setRightComponent(patientPanel);
        
    }//GEN-LAST:event_btnPatientActionPerformed

    private void btnInsuranceCoverageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsuranceCoverageActionPerformed
        // TODO add your handling code here:
        InsuranceJPanel insurancePanel = new InsuranceJPanel(insurance);
        jSplitPane1.setRightComponent(insurancePanel);
    }//GEN-LAST:event_btnInsuranceCoverageActionPerformed

    private void btnDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoctorActionPerformed
        // TODO add your handling code here:
        DoctorJPanel doctorPanel = new DoctorJPanel(doctor);
        jSplitPane1.setRightComponent(doctorPanel);
    }//GEN-LAST:event_btnDoctorActionPerformed

    private void btnDisplayPatientReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayPatientReportActionPerformed
        // TODO add your handling code here:
        
        DisplayJPanel displayPanel = new DisplayJPanel(person,address,insurance,patient,doctor,driver,vehicle);
        jSplitPane1.setRightComponent(displayPanel);
        
        
     // System.out.println("Person Name: "+person.getName());
              
               System.out.println("Person Name: "+person.getName());
     System.out.println(" Name: "+person.getAddress());
     System.out.println("Gender : "+person.getGender());
     System.out.println("Age: "+person.getAge());
     System.out.println("Email: "+person.getEmail());
     System.out.println("URL: "+person.getWebsiteUrl());
     System.out.println("Emergency Co 1: "+person.getEmergencyContact());
     System.out.println("Emergency Co 2: "+person.getEmergencyContact2());
     System.out.println("SSN: "+person.getSsn());
     System.out.println("Occupation: "+person.getOccupation());
    
    
    
     System.out.println("GPS location: "+address.getGpsLocation());
     System.out.println("City: "+address.getCity());
     System.out.println("State: "+address.getState());
     System.out.println("Country: "+address.getCountry());
    
    
    
     System.out.println("Benefits: "+insurance.getBenefits());
     System.out.println("Corporate ID: "+insurance.getCorporateID());
     System.out.println("Address: "+insurance.getAddress());
     System.out.println("Premium: "+insurance.getPremium());
     System.out.println("Deductable: "+insurance.getDeductable());
    
    
     System.out.println("Driver Name: "+driver.getDriversName());
     System.out.println("License No.: "+driver.getLicenseNo());
    
    
     System.out.println("Car Company: "+vehicle.getCarCompany());
     System.out.println("Model: "+vehicle.getModel());
     System.out.println("Chasis No: "+vehicle.getChasisNo());
     System.out.println("Serial No: "+vehicle.getSerial());
    
    
    
     System.out.println("Doctor Name: "+doctor.getName());
     System.out.println("Doctor ID: "+doctor.getDoctorsId());
     System.out.println("Specialist: "+doctor.getSpecialisedIn());
     System.out.println("Phone no: "+doctor.getPhoneNo());
     System.out.println("Address : "+doctor.getAddress());
     System.out.println("Email: "+doctor.getEmail());
     System.out.println("Website : "+doctor.getWebsite());
    
    
     System.out.println("Patient ID: "+patient.getPatientId());
     System.out.println("Primary Doctor: "+patient.getPrimaryDoctor());
     System.out.println("Date of visit: "+patient.getDateOfLastVisit());
     System.out.println("Next Appointment: "+patient.getDateOfNextAppointment());
        
           
        
        
    }//GEN-LAST:event_btnDisplayPatientReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddress;
    private javax.swing.JButton btnDisplayPatientReport;
    private javax.swing.JButton btnDoctor;
    private javax.swing.JButton btnDriver;
    private javax.swing.JButton btnInsuranceCoverage;
    private javax.swing.JButton btnPatient;
    private javax.swing.JButton btnPerson;
    private javax.swing.JButton btnVehicleRegistration;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
