/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import model.Patient;

/**
 *
 * @author HP
 */
public class PatientJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientJPanel
     */
    Patient patient;
    public PatientJPanel(Patient patient) {
        initComponents();
        this.patient = patient;
        ButtonGroup genderGroup = new ButtonGroup();
        
        
        ButtonGroup allergiesGroup = new ButtonGroup();
        allergiesGroup.add(radiobtnAllergiesYes);
        allergiesGroup.add(radiobtnAllergiesNo);
        
        
        ButtonGroup medicationGroup = new ButtonGroup();
        medicationGroup.add(radiobtnMedicationYes);
        medicationGroup.add(radiobtnMedicationNo);
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblPatientDetails = new javax.swing.JLabel();
        lblPatientId = new javax.swing.JLabel();
        lblPrimaryDoctor = new javax.swing.JLabel();
        lblDateOfLastVisit = new javax.swing.JLabel();
        lblDateOfNextAppointment = new javax.swing.JLabel();
        lblAllergies = new javax.swing.JLabel();
        lblMedication = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        txtPatientId = new javax.swing.JTextField();
        txtPrimaryDoctor = new javax.swing.JTextField();
        txtDateOfLastVisit = new javax.swing.JTextField();
        txtDateOfNextAppointment = new javax.swing.JTextField();
        radiobtnAllergiesYes = new javax.swing.JRadioButton();
        radiobtnAllergiesNo = new javax.swing.JRadioButton();
        radiobtnMedicationYes = new javax.swing.JRadioButton();
        radiobtnMedicationNo = new javax.swing.JRadioButton();

        lblPatientDetails.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblPatientDetails.setText("Patient details");

        lblPatientId.setText("Patient id");

        lblPrimaryDoctor.setText("Primary doctor");

        lblDateOfLastVisit.setText("Date of last visit");

        lblDateOfNextAppointment.setText("Date of next appointment");

        lblAllergies.setText("Allergies");

        lblMedication.setText("Medication");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        txtPrimaryDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrimaryDoctorActionPerformed(evt);
            }
        });

        radiobtnAllergiesYes.setText("Yes");

        radiobtnAllergiesNo.setText("No");
        radiobtnAllergiesNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobtnAllergiesNoActionPerformed(evt);
            }
        });

        radiobtnMedicationYes.setText("Yes");

        radiobtnMedicationNo.setText("No");
        radiobtnMedicationNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobtnMedicationNoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMedication)
                    .addComponent(lblDateOfNextAppointment)
                    .addComponent(lblPrimaryDoctor)
                    .addComponent(lblPatientId)
                    .addComponent(lblDateOfLastVisit)
                    .addComponent(lblAllergies))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDateOfLastVisit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                            .addComponent(txtPatientId)
                            .addComponent(txtPrimaryDoctor)
                            .addComponent(txtDateOfNextAppointment))
                        .addGap(253, 253, 253))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(radiobtnAllergiesYes)
                                .addGap(38, 38, 38)
                                .addComponent(radiobtnAllergiesNo))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(radiobtnMedicationYes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(radiobtnMedicationNo)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(btnSave))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(lblPatientDetails)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(lblPatientDetails)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPatientId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPatientId))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrimaryDoctor)
                    .addComponent(txtPrimaryDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDateOfLastVisit)
                    .addComponent(txtDateOfLastVisit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDateOfNextAppointment)
                    .addComponent(txtDateOfNextAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAllergies)
                    .addComponent(radiobtnAllergiesYes)
                    .addComponent(radiobtnAllergiesNo))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMedication)
                    .addComponent(radiobtnMedicationYes)
                    .addComponent(radiobtnMedicationNo))
                .addGap(18, 18, 18)
                .addComponent(btnSave)
                .addContainerGap(202, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1070, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        
        
         patient.setPatientId(txtPatientId.getText());
         patient.setPrimaryDoctor(txtPrimaryDoctor.getText());
         patient.setDateOfLastVisit(txtDateOfLastVisit.getText());
         patient.setDateOfNextAppointment(txtDateOfNextAppointment.getText());
         
         if(radiobtnAllergiesYes.isSelected()){
            patient.setAllergies(radiobtnAllergiesYes.getText());
        } else if(radiobtnAllergiesNo.isSelected()){
            patient.setAllergies(radiobtnAllergiesNo.getText());
        } 

        if(radiobtnMedicationYes.isSelected()){
            patient.setMedication(radiobtnMedicationYes.getText());
        } else if(radiobtnMedicationNo.isSelected()){
            patient.setMedication(radiobtnMedicationNo.getText());
        } 
         
         
        JOptionPane.showMessageDialog(this,"Patient Details Saved");
    }//GEN-LAST:event_btnSaveActionPerformed

    private void radiobtnMedicationNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiobtnMedicationNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radiobtnMedicationNoActionPerformed

    private void txtPrimaryDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrimaryDoctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrimaryDoctorActionPerformed

    private void radiobtnAllergiesNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiobtnAllergiesNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radiobtnAllergiesNoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAllergies;
    private javax.swing.JLabel lblDateOfLastVisit;
    private javax.swing.JLabel lblDateOfNextAppointment;
    private javax.swing.JLabel lblMedication;
    private javax.swing.JLabel lblPatientDetails;
    private javax.swing.JLabel lblPatientId;
    private javax.swing.JLabel lblPrimaryDoctor;
    private javax.swing.JRadioButton radiobtnAllergiesNo;
    private javax.swing.JRadioButton radiobtnAllergiesYes;
    private javax.swing.JRadioButton radiobtnMedicationNo;
    private javax.swing.JRadioButton radiobtnMedicationYes;
    private javax.swing.JTextField txtDateOfLastVisit;
    private javax.swing.JTextField txtDateOfNextAppointment;
    private javax.swing.JTextField txtPatientId;
    private javax.swing.JTextField txtPrimaryDoctor;
    // End of variables declaration//GEN-END:variables
}
