/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.*;

/**
 *
 * @author HP
 */
public class Admin1AddJPanel extends javax.swing.JPanel {

    /**
     * Creates new form Admin1AddJPanel
     */
    JPanel right;
    Admin2List admin2list;
      
    public Admin1AddJPanel(JPanel right, Admin2List admin2list) {
        initComponents();
        
        this.right = right;
        this.admin2list = admin2list; 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEmailId = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblNuId = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        lblMobileNumber = new javax.swing.JLabel();
        txtUserId = new javax.swing.JTextField();
        txtNuId = new javax.swing.JTextField();
        txtEmailId = new javax.swing.JTextField();
        lblUserId = new javax.swing.JLabel();
        txtMobileNumber = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        lblEmailId.setText("Email id");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Add new person");

        lblNuId.setText("NU id");

        btnSave.setBackground(new java.awt.Color(255, 51, 51));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblMobileNumber.setText("Mobile number");

        txtNuId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNuIdActionPerformed(evt);
            }
        });

        lblUserId.setText("User Id");

        btnBack.setBackground(new java.awt.Color(255, 102, 51));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(297, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUserId)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMobileNumber)
                            .addComponent(lblEmailId)
                            .addComponent(lblNuId, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(102, 102, 102)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUserId)
                            .addComponent(txtEmailId)
                            .addComponent(txtNuId)
                            .addComponent(txtMobileNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(420, 420, 420))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addGap(45, 45, 45)
                .addComponent(btnBack)
                .addGap(439, 439, 439))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnSave, jLabel5, lblEmailId, lblMobileNumber, lblNuId, lblUserId, txtEmailId, txtMobileNumber, txtNuId, txtUserId});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblUserId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txtUserId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblEmailId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txtEmailId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblNuId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txtNuId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblMobileNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txtMobileNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBack))
                .addGap(261, 261, 261))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        
             
            if(!(txtUserId.getText().chars().allMatch(Character::isDigit))){
                JOptionPane.showMessageDialog(null, "User ID should only be digits!");
                return;
            }
            
        

             if(txtUserId.getText().equals(""))
             {
                 JOptionPane.showMessageDialog(null, "Please enter User Id");
                 return;
             }
             
             if(txtEmailId.getText().equals("")){
                 JOptionPane.showMessageDialog(null, "Please enter Email ID");
                 return;
             }
             
             if(!isValidEmail(txtEmailId.getText())){
                JOptionPane.showMessageDialog(null, "Invalid email!", "Error", JOptionPane.ERROR_MESSAGE);      
                return;
            }        
             
             
             
             if(!(txtNuId.getText().chars().allMatch(Character::isDigit))){
                JOptionPane.showMessageDialog(null, "NU ID should only be digits!");
                return;
            }
             
             
             if(txtNuId.getText().equals(""))
             {
                 JOptionPane.showMessageDialog(null, "Please enter NU Id");
                 return;
             }
             
             if(txtMobileNumber.getText().equals(""))
             {
                 JOptionPane.showMessageDialog(null, "Please enter Mobile Number");
                 return;
             }
             if(!(txtMobileNumber.getText().chars().allMatch(Character::isDigit))){
                JOptionPane.showMessageDialog(null, "Mobile Number should only be digits!");
                return;
            }
             

        
        
        String userId = txtUserId.getText();
        String emailId = txtEmailId.getText();
        String nuId = txtNuId.getText();
        String mobileNumber = txtMobileNumber.getText();
        
        Admin1Add admin1add=admin2list.addPerson();
        // Adding new person reference
        admin1add.setNuId(nuId);
        admin1add.setEmailId(emailId);
        admin1add.setUserId(userId);
        admin1add.setMobileNumber(mobileNumber);
        
        JOptionPane.showMessageDialog(this,"Person Details Saved");
        
        
        txtUserId.setText("");
        txtEmailId.setText("");
        txtNuId.setText("");
        txtMobileNumber.setText("");
       
        
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        right.remove(this);
        CardLayout layout = (CardLayout) right.getLayout();
        layout.previous(right);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtNuIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNuIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNuIdActionPerformed

    private boolean isValidEmail(String email) {
        String regex = "^[A-Za-z0-9+_.-]+@([A-Za-z0-9.-]+)\\.(\\w{2,})$";
        return email.matches(regex);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblEmailId;
    private javax.swing.JLabel lblMobileNumber;
    private javax.swing.JLabel lblNuId;
    private javax.swing.JLabel lblUserId;
    private javax.swing.JTextField txtEmailId;
    private javax.swing.JTextField txtMobileNumber;
    private javax.swing.JTextField txtNuId;
    private javax.swing.JTextField txtUserId;
    // End of variables declaration//GEN-END:variables
}
