/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.*;

/**
 *
 * @author HP
 */
public class UserLoginJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UserLoginJPanel
     */
    JPanel right;
    Admin2List admin2List ; 
    Admin1Add admin1add;
    
    public UserLoginJPanel(JPanel right, Admin2List admin2list, Admin1Add admin1add) {
        initComponents();
        this.right = right;
        this.admin2List = admin2List; 
        this.admin1add= admin1add;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        btnUpdateInfo = new javax.swing.JButton();
        btnViewInfo = new javax.swing.JButton();

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        btnUpdateInfo.setBackground(new java.awt.Color(255, 102, 51));
        btnUpdateInfo.setText("Update info");
        btnUpdateInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateInfoActionPerformed(evt);
            }
        });

        btnViewInfo.setBackground(new java.awt.Color(255, 102, 51));
        btnViewInfo.setText("View info");
        btnViewInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUpdateInfo)
                    .addComponent(btnViewInfo))
                .addContainerGap(505, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(btnViewInfo)
                .addGap(38, 38, 38)
                .addComponent(btnUpdateInfo)
                .addContainerGap(369, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewInfoActionPerformed
        // TODO add your handling code here:
        UserViewJPanel panel18 = new UserViewJPanel(right, admin2List, admin1add);
        right.add("UserViewJPanel", panel18);
        CardLayout layout = (CardLayout) right.getLayout();
        layout.next(right);
        
    }//GEN-LAST:event_btnViewInfoActionPerformed

    private void btnUpdateInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateInfoActionPerformed
        // TODO add your handling code here:
//        int sri = tblList.getSelectedRow();
//       if (sri < 0)
//       {
//           JOptionPane.showMessageDialog(this, "Please Select a row to Create");
//           return;
//       }
//    DefaultTableModel model =(DefaultTableModel)tblList.getModel();
//       Admin1Add sv = (Admin1Add)model.getValueAt(sri, 0);
//      
//      
//                    txtUserName.setText(person.getUserName()) ;
//                    txtPassword.setText(person.getPassword());
//                    txtEmailId.setText(person.getEmailId());
//                    txtNuId.setText(person.getNuId());
//                    txtUserName.setText(person.getMobileNumber());

         UserUpdateJPanel panel17 = new UserUpdateJPanel(right, admin2List, admin1add);
        right.add("UserUpdateJPanel", panel17);
        CardLayout layout = (CardLayout) right.getLayout();
        layout.next(right);
    }//GEN-LAST:event_btnUpdateInfoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdateInfo;
    private javax.swing.JButton btnViewInfo;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables


//private void populateTable() {
//        
//    DefaultTableModel model = (DefaultTableModel) tblList.getModel();
//    model.setRowCount(0);
//    
//    for(Admin1Add vs : admin2list.getPersonList()){
//        Object[] row = new Object[7];
//        row[0] = vs;
//        //row[0] = vs.getUserId();
//        row[1] = vs.getNuId(); 
//        row[2] = vs.getEmailId();
//        row[3] = vs.getMobileNumber();
//        row[4] = vs.getUserName();
//        row[5] = vs.getPassword();
//        
//      
//        model.addRow(row);
//        
//        
//        
//    }
//    
//    }

}
