/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;


import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.*;

/**
 *
 * @author HP
 */
public class UserViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
     JPanel right;
     Admin2List admin2List;
      Admin1Add admin1add;
     

    public UserViewJPanel(JPanel right, Admin2List admin2list, Admin1Add admin1add) {
        initComponents();
            this.right = right;
            this.admin2List = admin2List;
            this.admin1add = admin1add;
            
            populatePersondetail();
    }
private void populatePersondetail()
    {
        txtUserId2.setText(admin1add.getUserId());
        txtNuId.setText(admin1add.getNuId());
        txtPassword2.setText(admin1add.getPassword());
        int size = admin1add.getPasswordlist().size() - 1;
        String lastHashed = admin1add.getPasswordlist().get(size);
        String p = String.join("", lastHashed);
        lblHashedPassword.setText(p);
        txtUserName.setText(admin1add.getUserName());
//        nametxt.setText(admin1add.getName());
        txtEmailId.setText(admin1add.getEmailId());
        txtMobileNumber.setText(admin1add.getMobileNumber());
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUserId = new javax.swing.JPanel();
        lblUserName = new javax.swing.JLabel();
        lblEmailId = new javax.swing.JLabel();
        headingViewUserDetails = new javax.swing.JLabel();
        lblNuId = new javax.swing.JLabel();
        lblPhoneNumber = new javax.swing.JLabel();
        txtUserName = new javax.swing.JLabel();
        txtEmailId = new javax.swing.JLabel();
        txtNuId = new javax.swing.JLabel();
        txtMobileNumber = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtPassword2 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        label = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUserId2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblHashedPassword = new javax.swing.JLabel();

        txtUserId.setBackground(new java.awt.Color(204, 204, 255));

        lblUserName.setText("User name");

        lblEmailId.setText("Email id");

        headingViewUserDetails.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        headingViewUserDetails.setText("View User details");

        lblNuId.setText("NU id");

        lblPhoneNumber.setText("Mobile number");

        lblPassword.setText("Password");

        btnBack.setBackground(new java.awt.Color(255, 102, 51));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        label.setText("User id");

        jLabel1.setText("Hashed password");

        javax.swing.GroupLayout txtUserIdLayout = new javax.swing.GroupLayout(txtUserId);
        txtUserId.setLayout(txtUserIdLayout);
        txtUserIdLayout.setHorizontalGroup(
            txtUserIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtUserIdLayout.createSequentialGroup()
                .addContainerGap(162, Short.MAX_VALUE)
                .addGroup(txtUserIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, txtUserIdLayout.createSequentialGroup()
                        .addComponent(headingViewUserDetails)
                        .addGap(265, 265, 265))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, txtUserIdLayout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(264, 264, 264))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, txtUserIdLayout.createSequentialGroup()
                        .addGroup(txtUserIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(lblUserName)
                            .addComponent(lblPassword)
                            .addComponent(lblEmailId)
                            .addComponent(lblNuId, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPhoneNumber)
                            .addComponent(label))
                        .addGroup(txtUserIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(txtUserIdLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                                .addGroup(txtUserIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(txtUserIdLayout.createSequentialGroup()
                                        .addComponent(txtUserId2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, txtUserIdLayout.createSequentialGroup()
                                        .addGroup(txtUserIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(txtUserIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtEmailId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtUserName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtNuId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtMobileNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)))
                                        .addGap(178, 178, 178))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, txtUserIdLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblHashedPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(122, 122, 122))))))
        );
        txtUserIdLayout.setVerticalGroup(
            txtUserIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtUserIdLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(headingViewUserDetails)
                .addGap(43, 43, 43)
                .addGroup(txtUserIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(txtUserIdLayout.createSequentialGroup()
                        .addGroup(txtUserIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUserName)
                            .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(txtUserIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPassword)
                            .addComponent(txtPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(txtUserIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(lblHashedPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(txtEmailId, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblEmailId))
                .addGap(33, 33, 33)
                .addGroup(txtUserIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNuId)
                    .addComponent(txtNuId, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(txtUserIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPhoneNumber)
                    .addComponent(txtMobileNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(txtUserIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUserId2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(txtUserIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(label)
                        .addComponent(jLabel3)))
                .addGap(23, 23, 23)
                .addComponent(btnBack)
                .addContainerGap(153, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(txtUserId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtUserId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
         right.remove(this);
        CardLayout layout = (CardLayout) right.getLayout();
        layout.previous(right);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel headingViewUserDetails;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel label;
    private javax.swing.JLabel lblEmailId;
    private javax.swing.JLabel lblHashedPassword;
    private javax.swing.JLabel lblNuId;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JLabel txtEmailId;
    private javax.swing.JLabel txtMobileNumber;
    private javax.swing.JLabel txtNuId;
    private javax.swing.JLabel txtPassword2;
    private javax.swing.JPanel txtUserId;
    private javax.swing.JLabel txtUserId2;
    private javax.swing.JLabel txtUserName;
    // End of variables declaration//GEN-END:variables
}
